#!/usr/bin/env bash

# init pyenv
if which pyenv > /dev/null; then
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init --path)";
    eval "$(pyenv init -)";
fi
