#!/usr/bin/env bash

export TMUXHOME="$HOME/.tmux"
export TMUXCONF="$TMUXHOME/.tmux.conf"

# run tmux from terminals only
PNAME="$(ps -o comm= $PPID)";
[ "$PNAME" == "gnome-terminal-" ] || \
    [[ "$PNAME" = *"iTerm2"* ]] || \
    [[ "$PNAME" = *"alacritty" ]] && \
    command -v tmux>/dev/null && \
    [ -z $TMUX ] && \
    tmux -f $TMUXCONF new-session -s init

