#!/usr/bin/env bash

export TMUXHOME="$HOME/.tmux"
export TMUXCONF="$TMUXHOME/.tmux.conf"

# run tmux from terminals only
PNAME="$(ps -o comm= $PPID)";
[ "$PNAME" == "gnome-terminal-" ] || \
    [[ "$PNAME" = *"alacritty" ]] && \
    command -v tmux>/dev/null && \
    [ -z $TMUX ] && \
    tmux -f $TMUXCONF new -s init\; \
    new -d -s ud-data\; \
    new -d -s ud-remote\; \
    new -d -s ud-code -c "$HOME/workspace/udemy"; \
    send-keys -t ud-code:1 'cd website-django;vim';
