#!/usr/bin/env bash

os=$(uname -s)

# Map mod keys for macOS
# Key codes are documented in
# https://developer.apple.com/library/archive/technotes/tn2450/_index.html
if [[ "$os" == Darwin ]] ; then
    # <CapsLock>      mapped to <Ctrl>
    # <Left-Ctrl>     mapped to <Esc>
    # <Section-sign>  mapped to <Esc>
    hidutil property --set '{"UserKeyMapping":
        [{"HIDKeyboardModifierMappingSrc":0x700000039,
          "HIDKeyboardModifierMappingDst":0x7000000e0},
         {"HIDKeyboardModifierMappingSrc":0x7000000E0,
          "HIDKeyboardModifierMappingDst":0x700000029},
         {"HIDKeyboardModifierMappingSrc":0x700000064,
          "HIDKeyboardModifierMappingDst":0x700000029}]
    }' > /dev/null
fi
